# Generated by Django 4.0.5 on 2022-07-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_View', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='location',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='Employee_name',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Employee_name',
        ),
    ]
